[tools]
actionlint = "1.7.9"
"cargo:cargo-about" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-fuzz" = "latest"
"cargo:cargo-geiger" = "latest"
"cargo:cargo-mutants" = "latest"
"cargo:cargo-tarpaulin" = "latest"
"cargo:release-plz" = "latest"
gh = "2.83.1"
"github:aboutcode-org/scancode-toolkit" = "latest"
go = "1.25.4"
"go:github.com/google/go-licenses/v2" = "v2.0.1"
golangci-lint = "2.6.2"
just = "1.43.1"
osv-scanner = "latest"
rust = "latest"
syft = "1.38.0"
yamllint = "1.37.1"
