[workspace]
# release notes via github, not in repo
changelog_update = false
git_release_enable = true
# renovate manages dependencies
dependencies_update = false


[[package]]
name = "lithos-gotmpl-engine"
publish = false

[[package]]
name = "lithos-gotmpl-core"
publish = false

[[package]]
name = "lithos-sprig"
publish = false
