[licenses]
"Apache-2.0" = ["LICENSE-APACHE"]
"MIT" = ["LICENSE-MIT"]
"BSD-3-Clause" = ["LICENSES/BSD-3-Clause.txt"]
"Unicode-DFS-2016" = ["LICENSES/Unicode-3.0.txt"]
"Unicode-3.0" = ["LICENSES/Unicode-3.0.txt"]
"BSL-1.0" = ["LICENSES/Boost-1.0.txt"]
"Unlicense" = ["LICENSES/UNLICENSE.txt"]
"LLVM-exception" = ["LICENSES/LLVM-exception.txt"]
"LGPL-2.1-or-later" = ["LICENSES/LGPL-2.1.txt"]
